// Weekday Tokyo BRT timetables used by bus.ts.
// Generated by scripts/scrape-brt.mjs (run weekly by .github/workflows/scrape-brt.yml).
// Hand edits are fine, but the next scrape that finds a change will overwrite them.
// Last changed: 2026-09-24
// Timetable as of: 2026年09月16日現在
// Sources: https://www.tokyo-brt.co.jp/bus-stops/b02-kachidoki-brt
//          https://www.tokyo-brt.co.jp/bus-stops/b11-toranomon-hills

export type BusSchedule = {
    [hour: number]: number[];
};

// Kachidoki BRT -> Toranomon Hills (Toranomon-bound departures only, not the Shimbashi ones)
export const brtKachidokiToToranomonBusTimes: BusSchedule = {
    6: [31, 46],
    7: [7, 28, 38, 42, 54],
    8: [1, 9, 15, 25, 31, 41, 51, 58],
    9: [6, 26, 46],
    10: [1, 16, 31, 51],
    11: [6, 26, 46],
    12: [6, 26, 46],
    13: [6, 26, 45],
    14: [1, 21, 36, 58],
    15: [11, 32, 46],
    16: [6, 21, 41],
    17: [1, 16, 31, 51],
    18: [6, 26, 41],
    19: [1, 15, 33, 50],
    20: [13, 32, 52],
    21: [12, 32, 52],
    22: [14]
};

// Toranomon Hills -> Kachidoki BRT (every departure)
export const brtToranomonToKachidokiBusTimes: BusSchedule = {
    6: [56],
    7: [11, 26, 48, 59],
    8: [5, 15, 20, 32, 35, 49, 55],
    9: [0, 10, 21, 30, 45],
    10: [5, 20, 40, 55],
    11: [15, 30, 45],
    12: [5, 25, 45],
    13: [5, 25, 45],
    14: [5, 25, 45, 55],
    15: [17, 30, 55],
    16: [10, 30, 45],
    17: [5, 20, 40, 55],
    18: [15, 30, 50],
    19: [0, 20, 35, 50],
    20: [10, 30, 50],
    21: [10, 30, 50],
    22: [10, 32]
};
